### ISSUE TITLE
Current Demo broken

### ISSUE THREAD

**Issue by mitchcapper** [Julien-Marcou/RadialMenu#1]
I am guessing its due to the commit from 9 hours ago but I get a blank screen on the demo after compiling currently.  The sample from the readme however works just fine.  Haven't had a chance to fully debug the demo yet.

**Comment by Julien-Marcou** [comment]
The RadialMenu in the demo opens when you perform a right click in the window ;)

**Comment by mitchcapper** [comment]
yeah I was an idiot, I looked at the code and saw that.  The VS 2015 new xaml debugger had me thinking it was visible.
