### ISSUE TITLE
Possibility to change the flow order?

### ISSUE THREAD

**Issue by zachatrocity** [Julien-Marcou/RadialMenu#7]
I'd like to be able to have a single arrow centered at the top of the menu rather than at the bottom. 

For example this:
![menu](https://cloud.githubusercontent.com/assets/6200670/9315038/564e2b9e-44f2-11e5-86b6-62125e80c8c1.png)

Would become like this:
![menuangle](https://cloud.githubusercontent.com/assets/6200670/9315213/6fdef75e-44f3-11e5-9208-3576014a5210.png)

With the labels the proper way of course. If you don't understand what I'm trying to say let me know.

**Comment by Julien-Marcou** [comment]
Nice suggestion =)

You should take a look at 81391edadf768ffed0a029c613d32bf7f129dedf
Now you can choose beetween the two using `HalfShiftedItems="True"`

**Comment by zachatrocity** [comment]
Awesome, thank you so much!
